### ISSUE TITLE
How to add widget in between the editor( page) content

### ISSUE THREAD

**Issue by geogeorgejoseph** [sojimaxi/grav-plugin-widget#10]
How to add widget in between the editor( page) content

**Comment by sojimaxi** [comment]
Hello @geogeorgejoseph  sorry for the late reply.  The best way to implement this is with a short code. Let me work on that and push a new update hopeful today. Thanks

**Comment by geogeorgejoseph** [comment]
Hello @sojimaxi is it ready ?

**Comment by sojimaxi** [comment]
@geogeorgejoseph  yes its ready.  using `[widget load="/widgets/_widget-name" ]`. Thanks for the patience.

**Comment by geogeorgejoseph** [comment]
thanks very much.
