### ISSUE TITLE
Create widgets button shows two times 

### ISSUE THREAD

**Issue by geogeorgejoseph** [sojimaxi/grav-plugin-widget#12]
Create widgets button shows two times 

![screenshots1](https://user-images.githubusercontent.com/25584016/32770951-476b0710-c947-11e7-96b9-8c36433b3167.png)
![screenshots2](https://user-images.githubusercontent.com/25584016/32772212-329c0664-c94b-11e7-9793-1a1362d8600f.png)

**Comment by sojimaxi** [comment]
Interesting but I tested the latest version with the latest version of Grav  and I can't seem to arrive at your screenshot.

**Comment by geogeorgejoseph** [comment]
After enabling  "Widgets in Widget " option the create widget buttons comes two times.
After disabling  that option one more button comes there.

**Comment by sojimaxi** [comment]
Okay. I did just that and I still can't arrive at your bug. My suggestion would be to note the current state of the plugin, then delete the plugin config file `widget.yaml` in `~/user/config/plugins`. Go back to the `widget` plugin in admin and modify the settings to match your previous state.

**Comment by geogeorgejoseph** [comment]
in admin.yaml file i found below code 2 times,after removing that code it worked perfectly

add_modals:
  -
    label: 'Create Widget'
    blueprint: admin/pages/widget_new
    show_in: bar
  -
    label: 'Create Widget'
    blueprint: admin/pages/widget_new
    show_in: bar

**Comment by sojimaxi** [comment]
I knew something similar might be the problem and that was why I suggest the config. Am happy you were able to resolve that thanks.
