### ISSUE TITLE
Change widget data in pages

### ISSUE THREAD

**Issue by Sogl** [sojimaxi/grav-plugin-widget#13]
Hello!

Found your plugin when looking for solution to my problem.

I want to create page from Admin with selected modular blocks. For example, we have non-routed non-visible page `/blocks` with all blocks list: `_intro`, `_testimonials`, `_products`, `_about` etc… and before create page user can select needed blocks from list and get full modular page with all of them.

Your plugin looks like solving my problem, but I need that user can edit content for selected blocks... like changing images or text in modular pages.

What do you think about it?
Theoretically, this would be a good addition to the plugin.

**Comment by sojimaxi** [comment]
@Sogl  Hi, and am very sorry for the late reply. 

It is a nice feature and also this feature may already exist. If you want to choose a different folder to load the widgets from, then look at the `Parent Folder` field in the`Widget` settings in `Dashboard -> Plugins`. 

You can change the text from "widgets" to "blocks" and make the plugin load widgets from the blocks folder then you can select them from the widget tab.

Also I would kindly need a clearer explanation. I can picture a mixture of feature that already exist and a new feature but can't really place your request. 

Thanks.

**Comment by Sogl** [comment]
>Also I would kindly need a clearer explanation. I can picture a mixture of feature that already exist and a new feature but can't really place your request.

Every widget have the same content on each page, right? I want to use different content for widget (copy original & edit it).
For example, we have widget with gallery (4 images and 3 blocks of text). I copy this widget from widgets folder using your plugin and can edit its content (delete and replace images, change text etc).

**Comment by sojimaxi** [comment]
Okay. 
This looks like you want Copy Widget button  that includes a list of all the current widgets available to be duplicated, instead of using the normal `Copy` button on the active page, so as to make it faster to duplicate page.
