### ISSUE TITLE
[Request] Remove redundancy in the "area" form dropdown

### ISSUE THREAD

**Issue by Heraes-git** [sojimaxi/grav-plugin-widget#16]
When defining the widgets area in the yaml : 
```
widget:
  areas: [top,bottom,left,right,content-flow]
```

It appears like this in the form dropdown : 

![2019-03-26_22h54m24s_chrome](https://user-images.githubusercontent.com/22033256/55036347-a50d6100-501a-11e9-8f2e-a3ba5613dff5.jpg)

What's in parenthesis always reflect the option name, so I don't find any interest in this and would like to remove it. **But I prefer to ask you before :** is there a utility for it, or can we remove it ?

I can't GIT push for now, I never used GIT commit, but here's the line concerned _(it's in widget.php, line 219)_ : 

```
self::$definedAreas[$item] = ucwords(strtr($item,'-',' '))." ($item)";
```
It seems that we could change it to : 
```
self::$definedAreas[$item] = ucwords(strtr($item,'-',' '));
```
but I'm not sure. Maybe you need the `." ($item)"` in order to send correct information to the form plugin for creating the form field. **Anyway, an idea on how remove the name redundancy would be appreciated. ;)**

**Comment by sojimaxi** [comment]
Fixed in version 1.3.2
