### ISSUE TITLE
[Request] Option to apply widgets to all sub-pages

### ISSUE THREAD

**Issue by Heraes-git** [sojimaxi/grav-plugin-widget#18]
This idea is different from the "global widgets".

While global widgets are intended to be displayed on all pages, I would like to set some widgets for a page, **and to display them also for all of its children**.

# Example

The Grav QUARK's theme provide a blog template, with a sidebar. Its concept is quite close to the _widget_ plugin, but necessitate to control the display directly in the frontmatter. Moreover, it is impossible to select what we want to display (it relies only on plugins enabling).

Thus, the _widget_ plugin could be a useful replacement : when creating a blog, we could decide wether we want or not to display some sidebars, and what we want in them. **But, in order for this to work, it implies that once defined some widgets for the parent's page, they keep displaying when routing to one child.**

**Comment by sojimaxi** [comment]
Added in version 1.4.0

**Comment by Heraes-git** [comment]
Thanks a lot ! You're a pro ! 🥇
