### ISSUE TITLE
Conflict with the new parent-page explorer of Grav

### ISSUE THREAD

**Issue by Heraes-git** [sojimaxi/grav-plugin-widget#19]
During a page creation, there's the possibility to chose in what parent page to insert the new page :

![2019-08-07_23h18m07s_chrome](https://user-images.githubusercontent.com/22033256/62662074-1ec33d00-b973-11e9-89a7-06260a4e473d.jpg)

But if the Widget plugin is activated, when clicking on the `<root>` button, the Javascript loads the treefile indefinitely, and never renders it : 

![2019-08-07_23h17m55s_chrome](https://user-images.githubusercontent.com/22033256/62662136-4a462780-b973-11e9-93d3-8921b2d91ad2.jpg)

After investigating with Chrome's inspector, it appears that the console returns an error right after having clicked on the button : 

![2019-08-07_23h19m48s_chrome](https://user-images.githubusercontent.com/22033256/62662155-5e8a2480-b973-11e9-934e-380d14992a90.jpg)

![2019-08-07_23h21m51s_chrome](https://user-images.githubusercontent.com/22033256/62662178-71045e00-b973-11e9-963b-463dfe888247.jpg)

# Additional information

An other plugin seems to conflict with the new Grav's ViewJS filetree explorer : `core-service-manager`, wich is used by the plugin `quicksave` (as a dependency). See the related ticket : https://github.com/Flamenco/grav-plugin-core-service-manager/issues/7

I have disabled all plugins and tested one by one, and obtained two different errors with the Widget plugin (infinite reload) and the Core-service-manager (no loading of the popup at all).

**Comment by sojimaxi** [comment]
Hi, seems good now. Fixed in v1.4.1. Thanks
