### ISSUE TITLE
Out-of-the-box unable to select Widget Template

### ISSUE THREAD

**Issue by awrog** [sojimaxi/grav-plugin-widget#2]
Just installed latest version of grav-plugin-widget (via plugin menu => Add...)
Try to create a widget [+ Create Widget]
I'm unable to select a widget template (dropdown will not open)

**Comment by sojimaxi** [comment]
@awrog  The widget template  are modular templates. you can put the template you need to use in the `modular` folder within your theme and they will come up. The `README` should contain all the information you need. Let me know if you are still having a problem. Thanks
