### ISSUE TITLE
Widget Plugin - Widget area location doesn't work

### ISSUE THREAD

**Issue by MohamedAlwash** [sojimaxi/grav-plugin-widget#20]
Hello every one!

I added Widget Plugin to my Grav project. It's working fine except one thing. When I change the widget location for e.x "Content-top" or "Content-bottom" it doesn't work. But when I set it to "Default" it works.
![Capture](https://user-images.githubusercontent.com/56513986/72731179-70fbc180-3b93-11ea-80d1-d8c92c2c2a08.PNG)

Someone has an idea what I am doing wrong?

**Comment by sojimaxi** [comment]
I think you may have not added the `{{ widget('content-top') }}`  or `{{ widget('content-bottom') }}` call in your twig template.
