### ISSUE TITLE
After update to 1.7.9 Widget plugin breaks the admin back-end

### ISSUE THREAD

**Issue by Crolug** [sojimaxi/grav-plugin-widget#23]
How to reproduce:

1. Install fresh Grav.
2. Install Admin plugin.
3. Install Widget plugin.

"Internal error" should pop up on the screen.

**Comment by yayayayaka** [comment]
Can confirm this behaviour. Perhaps it could be an upstream issue…

**Comment by sojimaxi** [comment]
@Crolug  thanks for bring this up.  Working on it now

**Comment by sojimaxi** [comment]
@Crolug it has been fixed in v1.5.0

**Comment by Crolug** [comment]
@sojimaxi Cheers mate!
