### ISSUE TITLE
How to disable the widgets fields from the content tab in each pages

### ISSUE THREAD

**Issue by geogeorgejoseph** [sojimaxi/grav-plugin-widget#4]
After installing widget plugin, some extra widgets fields comes in each page content section.i need that fields inside the particular widget not in the page content.
Can you suggest solution for this? 

![widgets](https://user-images.githubusercontent.com/25584016/28921260-cef5ca74-7872-11e7-9b77-714134865340.png)

**Comment by sojimaxi** [comment]
You can disable the widget extras from the widget plugin settings. Go `Plugins-> Widget -> Widget Extras`  then toggle to `Disable`. this will disable it for all pages

**Comment by geogeorgejoseph** [comment]
How can i enable this for some particular page templates

**Comment by sojimaxi** [comment]
You want it enabled for some templates in widgets or modular or page?
The feature is not selective yet.
Let me know your interest then i'll work on it and push out a new release

**Comment by geogeorgejoseph** [comment]
ok.

**Comment by sojimaxi** [comment]
@geogeorgejoseph  you haven't told me the template type? is it for modular or select pages?

**Comment by geogeorgejoseph** [comment]
Before creating a widget we need some templates for that particular widget so i need that widgets fields only for such templates.

**Comment by sojimaxi** [comment]
I publish  an update to the plugin to allow it enabled for all or widget only.
