### ISSUE TITLE
the widgets tab not comming in newly created page template

### ISSUE THREAD

**Issue by geogeorgejoseph** [sojimaxi/grav-plugin-widget#5]
The widgets tab appearing in blog and default page templates but not comes in newly created templates.
Can you suggest any solution for this issue.How to enable  this?

**Comment by sojimaxi** [comment]
The answer is in the `README` under theme config

**Comment by geogeorgejoseph** [comment]
Please share the command for enabling that ?

**Comment by geogeorgejoseph** [comment]
![new](https://user-images.githubusercontent.com/25584016/29110456-58e0bbd2-7d04-11e7-90bc-69505ef48fd2.png)
![default](https://user-images.githubusercontent.com/25584016/29110466-5f37b418-7d04-11e7-9380-36734ff260bc.png)

**Comment by sojimaxi** [comment]
@geogeorgejoseph what is the name of the template for the homepage

**Comment by geogeorgejoseph** [comment]
it is banner.html.twig

**Comment by sojimaxi** [comment]
For your use case lets assume the home template is called `banner.html.twig`.  Widget show up by default in standard pages but to enable it show in your custom page create a new ` banner.yaml`
in your theme's `blueprints` directory that extends the `default` blueprint.

```yaml
# Example Blueprint

# file: banner.yaml
title: Banner
'@extends': default

#... other configs
```
Or if that `banner.html.twig` is a modular template meaning that you will need to only `enable`  `Widgets in Widget` variable from the widget plugin settings.

**Comment by geogeorgejoseph** [comment]
Thanks. Now it's work fine.
