### ISSUE TITLE
Insert widget into page content?

### ISSUE THREAD

**Issue by CollinDaugherty** [sojimaxi/grav-plugin-widget#6]
Is it possible to insert the widget into the middle of {{ page.content }}

**Comment by sojimaxi** [comment]
Yes it's possible. Have you tried adding a twig code `{{ widget('content') }}` any where in the content and enable twig processing for that page?

Shortcodes would be best there. I tried keeping it lean and add features as they are needed.

**Comment by sojimaxi** [comment]
@CollinDaugherty this feature has been added in v.1.2.0
