### ISSUE TITLE
how to load particular grav widget using twig

### ISSUE THREAD

**Issue by geogeorgejoseph** [sojimaxi/grav-plugin-widget#9]
i am created one widget and it's name "test". how to call that widget inside the twig template.(i dont'want to add that widget from any particular page)

**Comment by SimpleByDesign** [comment]
Firstly have you added the widget locations into the theme you wish to add widgets too? (If so skip to the next bit...)

**Install on theme:**
To do this you add something like the following the the theme YAML file, this is the same name as the theme, for example for the antimatter theme you would edit antimatter.yaml.

Then add at the bottom of this file your widget locations:

widget:
  areas: [widgetheader,widgetsidebarleftbody,widgetfooter]

**Add widget to twig templates**
Then to add the widget location to the theme open the twig template in question, for example base.html.twig then add the following where you would like the widget to appear. This will load all the widgets that are located in widgetfooter in this example. This loads widgets you have created globally and ones that have been assigned to an individual page.

`{{ widget( 'widgetfooter') }}`

If you want to hide global widgets for a location such as widgetfooter and only show those you have assigned to a specific page then use the code:

`{{ widget('widgetfooter',false) }}`

To call any widget that is in the 'default' location you just need to use the following code where you would like the widgets to appear.

`{{ widget() }}`

The readme contains further information regarding widgets: https://github.com/sojimaxi/grav-plugin-widget/blob/master/README.md
